### ISSUE TITLE
The Classification files in the Nomenclature pack

### ISSUE THREAD

**Issue by LeneMartinsen** [orphanet-rare-diseases-issues/RD-CODE#2]
We have newly established a registry for rare disorders in Norway and the IT person responsible for incorporating the Orphanet nomeclature files has some questions we need help with. First question: What is the folder "Classifications_en" for? What is the purpose of the files in this folder? Does he need to import those as well or is that only if we want to report at higher levels (groups) in the classification? The purpose of this folder is unlcear to us.

I'm sure there will be more questions as we move along but let's start with this.

Kind regards,
Lene Martinsen
Orphanet Information Scientist

**Comment by Orphanet-disease-team** [comment]
Hello Lene,
"Classifications_en" are a set of files, each of which represents a medical specialty and includes all the entities grouped in this specialty, parents and children. It allows to rebuild the arborescence of the Orphanet classifications. The advantage to use these classification files is to have all the clinical entities, including groups, as you mentioned. Actually, ORPHA numbers of groups are mainly useful for undiagnosed patients or patients curently ongoing investigation and waiting for a precise diagnosis. Orphanet provides some documentation that may help IT person to better understand the structure of the data. They are accessible in [RD-code site] (http://www.rd-code.eu/introduction/)
and for more technical details see the [ORPHAnomenclature xml content](http://www.orphadata.org/cgi-bin/img/PDF/ORPHAnomenclaturexmlcontent.pdf).

Kind regards
Waed

**Comment by LeneMartinsen** [comment]
Hello Waed,
Thanks a lot for your reply.

Just to be clear: The classification files has to be imported if we want to register a patient at group level? It was not clear to me that the nomenclature file alone does not allow for groups since "groups of disorders" is mentioned as one of the tags in the nomenclature file (page 3 in DESCRIPTION OF THE ORPHANET NOMENCLATURE FILES FOR CODING doc): "DisorderListcount: total number of clinical entities (disorders, group of disorders or subtypes of disorder) in the Xml file.". It is also mentioned in the Appendix on page 17.

But when looking at "Example 4 Inactive entity referred to a group of disorders" it says that "As the ORPHAnumber of replacement ORPHA:183625 Rare genetic diabetes mellitus is of Group level, it cannot be used instead", so I guess this shows that group level is not an option in this file. It was a bit confusing to us whether coding at group level was allowed or not with the nomenclature file alone.

Another thing: I wonder if there is a mistake on page 14 in the DESCRIPTION OF THE ORPHANET NOMENCLATURE FILES FOR CODING doc. Under 3.2 Examples it says:

<DisorderList count="10462">
10462 is the total number of clinical entities in this XML file

but none of the classifications file has 10462 disorder list count. They all have: <DisorderList count="1"> on top of the file. Or have I misunderstood something? :)

All the best,
Lene

**Comment by Orphanet-disease-team** [comment]
Hello Lene
First of all, I confirm that groups can be used to code undiagnosed patients or patients with an unconfirmed diagnosis. It is why they are included, as well as disorders and subtypes of disorder in the nomenclature file. However, as you correctly mentioned, we do not provide the aggregation level for groups, as they will be multiples and we want to avoid the nomenclature file being cumbersome. Furthermore, as the aggregation level is multiple for groups, it is up to the nomenclature user to choose the accurate ORPHAcode depending on its use case. Several options are given to the user:
•	searching for the disorder on the Orphanet site and browse the classification to determine the group of interest belonging to the desired medical specialty.
•	implement the classification files provided in the nomenclature Pack in the user's system to display relationships between groups, disorders and subtypes.

Furthermore, I would like to highlight the importance to use the classification while searching for an ORPHA code. First, it eases the decision making process: for instance, searching in the nomenclature file for mucopolysaccharidosis retrieves 4 results, and looking at the classification allows to visually check that 3 of them are subtypes of the remaining code. Then, it also eases to carry out analysis on data collected. This analysis job can only be carried out thanks to the classification files (the website won't be the pertinent tool).

Concerning the bug in the “disorder list count” in xml classifications files, you're right, we check with the IT manager and this problem will be solved soon.

Regards,
Waed

**Comment by LeneMartinsen** [comment]
Thank you very much, Waed. We don't have the actual registry in front of us at the moment (the IT people are still working on implementing the files) but once we have it we'll take a look at the example you mention (mucopolysaccharidosis). 
We'll keep working on this and get back to you if we have more questions.

Best regards,
Lene

**Comment by houda-ali** [comment]
Hello Lene!
Following Waed's departure from Orphanet, I am trying to make sure we answer all requests coming through the GitHub. Should this issue be closed and if so, can you please do it? I'm not very familiar with this tool...
Thank you,
Houda

**Comment by LeneMartinsen** [comment]
Hello Houda!
Sorry for late reply. I'm closing this issue now - hopefully :)
All the best,
Lene
