### ISSUE TITLE
Translation of Orpha into ICD-11

### ISSUE THREAD

**Issue by ghost** [orphanet-rare-diseases-issues/RD-CODE#3]
Dear Orpha Team,
We are currently setting up a patient registry for rare patients with multi-organ Autoimmunity in cooperation with the European ESID Registry. We want to document also the diagnosis of the patients using a uniform code. As currently, the clinics are documenting in a combination of ICD-10 and Orpha Codes - but the german clinics need to move to ICD-11, we wonder if there is a possibility to translate OrphaNet codes to ICD-11 codes as they should be linked by an URI (Uniform Resource Identifier). 
In the tool which is planned to be released in December, it is mentioned that a translation to ICD-10 is possible. As ICD-10 is outdated now with the new version of ICD-11 - is it also possible to translate Orphan codes to ICD-11 with the upcoming release? And at what time would this be available?
Thank you very much in advance!
Best wishes,
Paulina Staus
i.A. GAIN registry

**Comment by Orphanet-disease-team** [comment]
Dear Paulina,
Currently we are working with WHO on the cross-referencing with ICD-11, which will be available by mid-2020 in Orphanet site. However concerning the implementation files and the API tool, we don't have an agenda yet, once I have more details I will inform you. 
Regards,
Waed

**Comment by ghost** [comment]
Dear Waed,

Are there news about this? I could not find a cross-referencing file yet. Is it available?
Thank you in advance
Best wishes
Paulina

**Comment by houda-ali** [comment]
Dear Paulina,
The Orphanet-ICD-11 alignment has not yet been implemented in our database due to several delays on this work for various reasons, one of them being the pandemic which has considerably impacted the recruitment process on this position.
We are hoping to be able to provide it in the next coming months.
Thank you for your understanding.
Houda

**Comment by JTorphanet** [comment]
Dear @GAIN-registry,

Sorry for this late reply. ICD11 alignment is now available on Orphanet website and the complete list can be downloaded in the Nomenclature Pack. As of today, we have aligned about 2000 ORPHAcodes with ICD-11, corresponding to 32% of ORPHAcodes of which 20% with an exact relationship. We have started a close collaboration with WHO to introduce rare diseases with the best possible representation in ICD-11. Moreover, not all rare diseases in the ICD-11 will have a specific code, but the majority of rare diseases will be represented in the Foundation with an URI that will correspond to a larger ICD-11 code. In the next coming weeks, we will provide a document available on the GitHub OD4RD [WikiPage] (https://github.com/OD4RD/Main-Help-Desk/wiki/Alignements-with-others-terminologies) to explain the alignment process. 

Best regards, 

Julie

**Comment by ghost** [comment]
Dear Julie,

thank you for the notice! This will be usefull for our further development of the registry.

Best wishes and a good Christmas time,
Paulina Staus



Von: Julie T. - ORPHANET ***@***.***>
Gesendet: Freitag, 16. Dezember 2022 10:23
An: orphanet-rare-diseases-issues/RD-CODE ***@***.***>
Cc: Paulina Ines Staus ***@***.***>; Mention ***@***.***>
Betreff: Re: [orphanet-rare-diseases-issues/RD-CODE] Translation of Orpha into ICD-11 (#3)


Dear @GAIN-registry<https://github.com/GAIN-registry>,

Sorry for this late reply. ICD11 alignment is now available on Orphanet website and the complete list can be downloaded in the Nomenclature Pack. As of today, we have aligned about 2000 ORPHAcodes with ICD-11, corresponding to 32% of ORPHAcodes of which 20% with an exact relationship. We have started a close collaboration with WHO to introduce rare diseases with the best possible representation in ICD-11. Moreover, not all rare diseases in the ICD-11 will have a specific code, but the majority of rare diseases will be represented in the Foundation with an URI that will correspond to a larger ICD-11 code. In the next coming weeks, we will provide a document available on the GitHub OD4RD [WikiPage] (https://github.com/OD4RD/Main-Help-Desk/wiki/Alignements-with-others-terminologies) to explain the alignment process.

Best regards,

Julie
