### ISSUE TITLE
ICD10 mapping - use of "not yet validated" codes

### ISSUE THREAD

**Issue by LeneMartinsen** [orphanet-rare-diseases-issues/RD-CODE#4]
Hi,
We wonder if RD-Code or Orphanet have any recommendations regarding the use of the ICD-10 codes in the mapping file that has not yet been validated? Do you recommend to include them when we implement the file in the national registry for rare disorders or should we exclude them? When I do a counting it seems to be 120 ICD10 codes not yet validated (I read the file in UltraEdit).

Kind regards,
Lene
Norway

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

Sorry, for this late reply. Alignment process follows a specific step-by-step procedure with 2 validations from the Orphanet scientific committee. The "Not yet validated" mention means that only 1 validation has been performed. In the meantime, we are working on this specific list to validate the remaining codes (as of today, about 400 ORPHAcodes). 

I invite you to join the new GitHub (https://github.com/OD4RD) if you have more questions !

Best, 

Julie
