### ISSUE TITLE
Advice for the resolution of the mapping of ORPHAcodes to ICD10ES

### ISSUE THREAD

**Issue by rico-juamol** [orphanet-rare-diseases-issues/RD-CODE#5]
Dear colleagues and collaborators of the RD-CODE project. After completing the task of mapping the ORPHAcodes from the “Master file for Statistical reporting with Orphacodes” to the ICD-10-ES (stems from ICD-10-CM) employed for diagnoses coding at the Spanish Healthcare System, we have reached an impasse. We haven´t been able to attain consensus for the ICD-10-ES codes of 111 ORPHAcodes. We have revised them several times and have proposed some provisional codes but would like to refine the mapping to keep only one ICD-10-ES code as equivalent always that this is possible.
We share here an excel file containing the ORPHAcodes in this situation, along with the potential ICD-10-ES codes matching them we have considered. We also provide explanatory documents to understand the contents of the excel file and details about the procedure and criteria we have followed for the mapping of ORPHAcodes to ICD-10-ES.
We ask you to have a look at the list of ORPHAcodes and share with us, if possible, the equivalences you have established for them (if any) to ICD-10, ICD-10-CM or the version derived from them that you are using in your country or the criteria you would use to filter them. This way we aim to narrow the list of potential ICD-10-ES codes equivalent to each of these ORPHAcodes and also keep the homogeneity with what has been done in different countries.
Many thanks for your collaboration.
Any help would be welcome.
Sincerely.
Juan
[Guidelines for the ORPHAtoICD equivalences document FISABIO_rev.docx](https://github.com/orphanet-rare-diseases-issues/RD-CODE/files/5481059/Guidelines.for.the.ORPHAtoICD.equivalences.document.FISABIO_rev.docx)
[ORPHA to ICD10ES.xlsx](https://github.com/orphanet-rare-diseases-issues/RD-CODE/files/5481060/ORPHA.to.ICD10ES.xlsx)
[Procedure for the mapping of ORPHAcodes to ICD10ES in Spain FISABIO_rev.docx](https://github.com/orphanet-rare-diseases-issues/RD-CODE/files/5481063/Procedure.for.the.mapping.of.ORPHAcodes.to.ICD10ES.in.Spain.FISABIO_rev.docx)

**Comment by Orphanet-disease-team** [comment]
Thank you for sharing with us these un-solved ICD10-ES cross-referencing codes as well as your working method. I hope we hear from persons/coders concerned by this issue.

**Comment by JTorphanet** [comment]
Dear @rico-juamol, 

Sorry for this late reply. Unfortunately, Orphanet is an international classification and by definition, aligned only with other international medical classifications. We understand that countries needed to update ICD10 over time while waiting for ICD11, but it is technically not possible to align ORPHAcodes with all the country-specific ICD10-CM systems. Most of the time, the “national” ICD10-CM database is more granular. Up-to-date, we have aligned 71% of active entities with a ICD10 code and more than 89% at the disorder level. Our general advice is to use the alignment provided by Orphanet to help you to find the right group and use it to refine the alignment to the national ICD10-CM step by step. 

I invite you to join the new GitHub [OD4RD GitHub](https://github.com/OD4RD) if you have more questions!

Best, 

Julie
